#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=24)
timezone=$(cat /etc/timezone)

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
authsecret=$(openssl rand -hex 32)
secretkey=$(openssl rand -hex 32)
cat > "$install_dir/.env" <<EOL
AUTH_SECRET="$authsecret"
SECRET_ENCRYPTION_KEY=$secretkey
LOG_LEVEL='info'
DB_DRIVER='better-sqlite3'
DB_URL='$install_dir/db.sqlite'
TURBO_TELEMETRY_DISABLED=1
EOL

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Customizable browser's home page"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

#=================================================
# INSTALL HOMARR
#=================================================
ynh_script_progression "Building the app..."

pushd $install_dir
    ynh_hide_warnings corepack enable
    ynh_hide_warnings corepack prepare pnpm@latest --activate
    # ynh_hide_warnings ynh_exec_as_app COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm install
    # ynh_hide_warnings ynh_exec_as_app pnpm run db:migration:sqlite:run
    # ynh_hide_warnings ynh_exec_as_app NODE_ENV=production pnpm run build
    ynh_hide_warnings ynh_exec_as_app yarn install
    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
    ynh_hide_warnings ynh_exec_as_app yarn run db:migration:sqlite:run
    ynh_hide_warnings ynh_exec_as_app mkdir -p build
    ynh_hide_warnings ynh_exec_as_app cp ./node_modules/better-sqlite3/build/Release/better_sqlite3.node ./build/better_sqlite3.node
    chown -R "$app:$app" "$install_dir"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
